/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BankAccount } from "./BankAccount";
export * as factories from "./factories";
export { BankAccount__factory } from "./factories/BankAccount__factory";
